### ISSUE TITLE
set up ci/cd for this repo

### ISSUE THREAD

**Issue by soltanianalytics** [Gemma-Analytics/gemma-dbt-utils#3]
Goal: Utilize testing to ensure quality and correctness of macros.

Can be implemented much as fishtown's own dbt-utils: https://github.com/fishtown-analytics/dbt-utils

**Comment by soltanianalytics** [comment]
done: set up basic circleci (mostly copied appropriate files from Fishtown's dbt utils)

open:
- understand and implement environment caching (see https://github.com/fishtown-analytics/dbt-utils/blob/master/.circleci/config.yml steps `restore_cache` and `save_cache`)
- understand, implement and describe local testing procedure
- set up circleci to set in PRs only and not with every push

**Comment by Dimi727** [comment]
caching is a manual optimization topic and not a setting we can enable. we need to think about every deploy how and where to use caching. mostly it's important for heavy build steps like pip install dbt.

**More info: https://circleci.com/docs/2.0/caching/
For automated docker caching (premium paid feature): https://circleci.com/docs/2.0/docker-layer-caching/**

**Comment by Dimi727** [comment]
the local testing procedure needs Linux/mac. 
Is possible by setting up Linux subsystem on Windows, but will be handled in a separate issue

**Comment by soltanianalytics** [comment]
PR merged
